import { friendsType } from "../types"
import UserCard  from "../utils/UserCard";


export default function Friend_Cards() {

    return (
        <div className=" grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-2">
            {
                friends.map((friend) => (
                    <div className="">
                        {<UserCard data={friend} />}
                    </div>
                ))
            }
        </div>
    )
}


const friends: friendsType[] = [
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: false,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: false,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: false,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: false,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    {
        name: 'Ahmed Nasser',
        bio: 'JavaSctipt Devloper',
        friends: 99,
        projects: 15,
        articls: 25,
        joined: '02/10/2021',
        vip: true,
    },
    
]